// 开局角色池：completeSetup 从这里洗牌后给盗梦者分配角色。
// 必须与共享卡牌数据里的全部盗梦者角色一致，由 characterPool.test.ts 对账。

import type { CardID } from '@icgame/shared';

export const THIEF_POOL: readonly CardID[] = [
  'thief_pointman',
  'thief_dream_interpreter',
  'thief_space_queen',
  'thief_joker',
  'thief_leo',
  'thief_tourist',
  'thief_capricornus',
  'thief_chemist',
  'thief_paprik',
  'thief_lord_of_war',
  'thief_libra',
  'thief_sudger_of_mind',
  'thief_scorpius',
  'thief_taurus',
  'thief_apollo',
  'thief_athena',
  'thief_architect',
  'thief_virgo',
  'thief_haley',
  'thief_martyr',
  'thief_soul_sculptor',
  'thief_shade',
  'thief_hlnino',
  'thief_extractor',
  'thief_forger',
  'thief_terrorist',
  'thief_black_hole',
  'thief_black_swan',
  'thief_gemini',
  'thief_pisces',
  'thief_luna',
  'thief_aries',
  'thief_gaia',
  'thief_sagittarius',
  'thief_aquarius',
  'thief_green_ray',
  'thief_darwin',
  'thief_cancer',
] as CardID[];
