#!/usr/bin/env npx tsx
// cards-data.json → TypeScript 生成脚本
// 输入：plans/assets/cards-data.json
// 输出：packages/shared/src/cards/generated/cards.ts

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../../../../');
const INPUT = resolve(ROOT, 'plans/assets/cards-data.json');
const OUTPUT = resolve(__dirname, '../src/cards/generated/cards.ts');

interface RawCard {
  id: string;
  name: string;
  quantity?: number;
  type?: string;
  sides?: Array<{
    side: string;
    name: string;
    image: string;
    skills?: Array<{ name: string; description: string }>;
    analyze?: string;
  }>;
  image?: string;
  description?: string;
}

interface RawData {
  cards: {
    thief: RawCard[];
    'dream-master': RawCard[];
    action: RawCard[];
    dream: RawCard[];
    bribe: RawCard[];
    vault: RawCard[];
    nightmare: RawCard[];
    other: RawCard[];
  };
}

// 图片路径规范化：cards-data.json 里的 OCR 源用的是 .jpg 扩展名，
// 但对外产物要使用 plans/scripts/convert-to-webp.sh 预压缩过的 .webp 版本，
// 同时剥掉前导 "cards/" 前缀，改为相对 /public/cards/ 根的路径（由 CardImage 组件补前缀）。
function normalizeImagePath(src: string): string {
  if (!src) return '';
  const webp = src.replace(/\.(jpg|jpeg|png)$/i, '.webp');
  return webp.replace(/^cards\//, '');
}

function main() {
  const raw: RawData = JSON.parse(readFileSync(INPUT, 'utf-8'));

  mkdirSync(dirname(OUTPUT), { recursive: true });

  const lines: string[] = [];
  lines.push('// ⚠️ AUTO-GENERATED by scripts/codegen.ts — DO NOT EDIT');
  lines.push(`// Source: plans/assets/cards-data.json`);
  lines.push(`// Generated: ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  // 角色牌（盗梦者 + 梦主）
  const thiefChars = raw.cards.thief.map(cardToCharacter('thief'));
  const masterChars = raw.cards['dream-master'].map(cardToCharacter('master'));

  // 行动牌
  const actionCards = raw.cards.action.map(cardToAction);

  // 梦魇牌
  const nightmareCards = raw.cards.nightmare.map(cardToNightmare);

  // 梦境牌
  const dreamCards = raw.cards.dream.map(cardToDream);

  // 金库牌
  const vaultCards = raw.cards.vault.map(cardToVault);

  // 贿赂牌
  const bribeCards = raw.cards.bribe.map(cardToBribe);

  // 写入
  lines.push('import type {');
  lines.push('  CharacterDefinition, ActionCardDefinition, NightmareCardDefinition,');
  lines.push('  DreamCardDefinition, VaultCardDefinition, BribeCardDefinition,');
  lines.push('} from "../../types/cards.js";');
  lines.push('');
  lines.push(
    `export const THIEF_CHARACTERS: readonly CharacterDefinition[] = ${JSON.stringify(thiefChars, null, 2)} as const;`,
  );
  lines.push('');
  lines.push(
    `export const MASTER_CHARACTERS: readonly CharacterDefinition[] = ${JSON.stringify(masterChars, null, 2)} as const;`,
  );
  lines.push('');
  lines.push(
    `export const ACTION_CARDS: readonly ActionCardDefinition[] = ${JSON.stringify(actionCards, null, 2)} as const;`,
  );
  lines.push('');
  lines.push(
    `export const NIGHTMARE_CARDS: readonly NightmareCardDefinition[] = ${JSON.stringify(nightmareCards, null, 2)} as const;`,
  );
  lines.push('');
  lines.push(
    `export const DREAM_CARDS: readonly DreamCardDefinition[] = ${JSON.stringify(dreamCards, null, 2)} as const;`,
  );
  lines.push('');
  lines.push(
    `export const VAULT_CARDS: readonly VaultCardDefinition[] = ${JSON.stringify(vaultCards, null, 2)} as const;`,
  );
  lines.push('');
  lines.push(
    `export const BRIBE_CARDS: readonly BribeCardDefinition[] = ${JSON.stringify(bribeCards, null, 2)} as const;`,
  );

  // 统计
  const total =
    thiefChars.length +
    masterChars.length +
    actionCards.length +
    nightmareCards.length +
    dreamCards.length +
    vaultCards.length +
    bribeCards.length;

  lines.push('');
  lines.push(`// 合计 ${total} 张卡牌定义`);
  lines.push(`export const ALL_CARD_COUNT = ${total} as const;`);

  writeFileSync(OUTPUT, lines.join('\n'));
  console.log(`✅ Generated ${total} card definitions → ${OUTPUT}`);
}

function cardToCharacter(faction: 'thief' | 'master') {
  return (card: RawCard) => {
    const front = card.sides?.find((s) => s.side === 'front');
    const back = card.sides?.find((s) => s.side === 'back');
    const isDouble = !!back?.skills?.length;

    return {
      category: faction === 'thief' ? ('thief_char' as const) : ('master_char' as const),
      id: card.id,
      name: card.name,
      faction,
      doubleSided: isDouble,
      front: {
        sideName: front?.name ?? card.name,
        skills:
          front?.skills?.map((s, i) => ({
            id: `${card.id}.skill_${i}`,
            name: s.name,
            description: s.description,
            trigger: 'onActionPhase' as const,
            usageScope: 'ownTurnOncePerTurn' as const,
            isActive: true,
          })) ?? [],
      },
      ...(isDouble
        ? {
            back: {
              sideName: back!.name,
              skills: back!.skills!.map((s, i) => ({
                id: `${card.id}.back.skill_${i}`,
                name: s.name,
                description: s.description,
                trigger: 'onActionPhase' as const,
                usageScope: 'ownTurnOncePerTurn' as const,
                isActive: true,
              })),
            },
          }
        : {}),
      imagePath: normalizeImagePath(front?.image ?? ''),
      isExpansion: false,
    };
  };
}

function cardToAction(card: RawCard) {
  return {
    category: 'action' as const,
    id: card.id,
    name: card.name,
    subType: 'shoot_basic' as const,
    quantity: 1,
    isExpansion: false,
    isRemovedAfterUse: false,
    timing: ['actionPhase' as const],
    targetSpec: { kind: 'otherPlayer' as const },
    effects: [],
    imagePath: normalizeImagePath(card.image ?? ''),
  };
}

function cardToNightmare(card: RawCard) {
  return {
    category: 'nightmare' as const,
    id: card.id,
    name: card.name,
    description: card.description ?? '',
    imagePath: normalizeImagePath(card.image ?? ''),
  };
}

function cardToDream(card: RawCard) {
  return {
    category: 'dream' as const,
    id: card.id,
    name: card.name,
    description: card.description ?? '',
    imagePath: normalizeImagePath(card.image ?? ''),
  };
}

function cardToVault(card: RawCard) {
  return {
    category: 'vault' as const,
    id: card.id,
    name: card.name,
    description: card.description ?? '',
    imagePath: normalizeImagePath(card.image ?? ''),
  };
}

function cardToBribe(card: RawCard) {
  return {
    category: 'bribe' as const,
    id: card.id,
    name: card.name,
    description: card.description ?? '',
    imagePath: normalizeImagePath(card.image ?? ''),
  };
}

main();
