// 卡图清单的数据结构与生成逻辑（纯函数）
//
// scripts/cardImageManifest.ts 读出 public/cards 下的文件后交给这里描述与排版，写成
// generated/cardImageManifest.ts；cardImageManifest.test.ts 用同一套函数核对入库的清单。
// 运行时的应用代码不引用这个文件（运行时只读生成出来的清单，见 cardImageVersion.ts）。

import { parseWebpInfo } from './webpInfo';

export interface CardImageManifestEntry {
  /** 文件内容 SHA-256 的前 HASH_LENGTH 位十六进制，作卡图地址的版本参数 */
  readonly hash: string;
  /** 文件字节数 */
  readonly bytes: number;
  /** 画布宽高（像素） */
  readonly width: number;
  readonly height: number;
}

/** 版本参数的长度：一百来张图，只用来区分同一路径下内容是否变过，十位十六进制足够 */
export const HASH_LENGTH = 10;

export function shortHash(sha256Hex: string): string {
  if (!/^[0-9a-f]{64}$/.test(sha256Hex)) throw new Error('sha256 应为 64 位小写十六进制');
  return sha256Hex.slice(0, HASH_LENGTH);
}

/** 描述一张卡图：哈希由调用方给（脚本用 node:crypto，测试用 Web Crypto），尺寸由文件头解析 */
export function describeCardImage(bytes: Uint8Array, sha256Hex: string): CardImageManifestEntry {
  const info = parseWebpInfo(bytes);
  return {
    hash: shortHash(sha256Hex),
    bytes: bytes.length,
    width: info.width,
    height: info.height,
  };
}

const HEADER = [
  '// ⚠️ AUTO-GENERATED by scripts/cardImageManifest.ts — DO NOT EDIT',
  '// Source: public/cards 下的卡图文件（pnpm --filter @icgame/client cards:manifest）',
  '',
].join('\n');

/** 渲染成 TypeScript 源码（键按路径排序，未排版；脚本负责交给 prettier） */
export function renderCardImageManifestModule(
  entries: Readonly<Record<string, CardImageManifestEntry>>,
): string {
  const sorted = Object.fromEntries(
    Object.entries(entries).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
  );
  return [
    HEADER,
    "import type { CardImageManifestEntry } from '../cardImageManifestBuild';",
    '',
    '// 键是相对 public/cards 的路径（与卡牌配置里的 imagePath 一致），值是文件的内容哈希、字节数与宽高',
    `export const CARD_IMAGE_MANIFEST: Readonly<Record<string, CardImageManifestEntry>> = ${JSON.stringify(sorted, null, 2)};`,
    '',
  ].join('\n');
}
