// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // 预设短语与成就定义的初始数据；幂等，部署时紧跟 migrate deploy 之后执行
    seed: 'tsx src/seed/run.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
